Roll Depot Tools from fa63ec743710 to 20ce2373ddbe (8 revisions) Android Bringup: See http://go/android-fw-sync
Android Bringup: See http://go/android-fw-sync

2025-09-04 rop@google.com Fix: Use f-string for validation warning message.
2025-09-04 rop@google.com Checking for package managers in vuln sufficiency.
2025-09-04 ukai@google.com siso: add .sisorc support
2025-09-04 ayatane@chromium.org auth: Refactor missing access_token logic
2025-09-04 ukai@google.com ninja: fix TypeError: check_out_dir() missing 1 required positional argument
2025-09-03 ayatane@chromium.org auth: Remove unused param
2025-09-03 ayatane@chromium.org auth: Hoist exception handling in GerritAuthenticator
2025-09-03 ayatane@chromium.org auth: Disable ReAuth for git-credential-luci in depot_tools

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
Please CC chromeos-build-team@google.com,lovisolo@google.com,rrangel@google.com on the revert to ensure that a human
is aware of the problem.

To file a bug in ChromeOS: https://bugs.chromium.org/p/chromium/issues/entry

To report a problem with the AutoRoller itself, please file a bug:

Documentation for the AutoRoller is here:

(cherry picked from commit c415f3ab8d2d01198751da0a19433243d8d3749f)

Original-Original-https: //chromium.googlesource.com/chromium/tools/depot_tools.git/+log/fa63ec743710..20ce2373ddbe
Original-Original-https: //skia-autoroll.corp.goog/r/depot-tools-chromeos
Original-Original-https: //issues.skia.org/issues/new?component=1389291&template=1850622
Original-Original-https: //skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
Original-Original-Bug: chromium:438384047,chromium:442612621,chromium:442666611
Original-Original-Tbr: lovisolo@google.com,rrangel@google.com
Change-Id: I4407dd53ec0974176a85e0a235e32501d47f4f98
Original-Original-Reviewed-on: https://chrome-internal-review.googlesource.com/c/chromeos/manifest-internal/+/8567976
Original-Original-Commit-Queue: chromium-internal-autoroll <chromium-internal-autoroll@skia-corp.google.com.iam.gserviceaccount.com>
Original-Original-Bot-Commit: chromium-internal-autoroll <chromium-internal-autoroll@skia-corp.google.com.iam.gserviceaccount.com>
Original-GitOrigin-RevId: c415f3ab8d2d01198751da0a19433243d8d3749f
Original-Cr-Build-Id: 8704604365502157361
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8704604365502157361
Original-Copybot-Job-Name: android-main-manifest-internal-copybot-downstream
Original-Reviewed-on: https://chrome-internal-review.googlesource.com/c/chromeos/manifest-internal/+/8567046
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Reviewed-by: Jon Murphy <jpmurphy@google.com>
GitOrigin-RevId: 2c950a28441f8fc4e96d07714cf21c1bbc08b984
Cr-Build-Id: 8704264626929777857
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8704264626929777857
Copybot-Job-Name: android-main-fw-public-manifest-manifest-internal-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/manifest/+/6925864
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>